### PR TITLE
Fix readme licensing issues.

### PR DESCRIPTION
**Pull request by jojolepro**
If this isn't merged, the repository is liable to licensing infringement, which can lead to your account's termination.

Its not just about respecting licenses, its about respecting other's work. If you want to be respected, respect others.

### CODE REVIEW

**Comment by botika** [comment]
It is not a fork, it is just a derivation with the structure of a compiler. I'm not going to give you an acknowledgment that you do not deserve. What parts do not comply with the license? Can you pass the links to me, please? I will change everything that does not comply with the license. Thank you.

**Comment by jojolepro** [comment]
> It is not a fork, it is just a derivation

So this is a derivation of Askama? I'm not sure I understand...

**Comment by botika** [comment]
https://doc.rust-lang.org/rust-by-example/trait/derive.html

**Comment by botika** [comment]
close in favor of #29

**Pull request closed without merging**
